language: python 
cache: pip
jobs:
  include:
  - stage: test
    name: "Code Formatting"
    python: 3.6
    before_script:
    - pip install black==19.3b0
    script:
    - black --check src
  - stage: deploy
    name: "Deploy"
    python: 3.6
    install: pip install pipdate
    script: pip install requests
    deploy:
      skip_cleanup: true
      provider: script
      script: 
      - pip show pipdate
      - pip show requests