dist: xenial
jobs:
  include:
    - stage: deploy
      if: tag IS present
      name: "Deploy!"
      script: skip
      install: skip
      deploy:
        provider: script
        on:
          tags: true
        script: echo "DEPLOYING NOW"
